version: '3.9'
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8000:80

  db:
    image: mysql:5.7
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: library_db
    ports:
      - 3306:3306