import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { BooksProvider } from '@/context/BooksContext';
import { FavoriteProvider } from '@/context/FavoriteContext';
import { CartProvider } from '@/context/CartContext';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: "Web-Library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <BooksProvider>
            <FavoriteProvider>
              <CartProvider>
                {children}
              </CartProvider>
            </FavoriteProvider>
          </BooksProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
